# Pypyrus

WARNING: Currently in development, not ready for production

Pypyrus is a file generation tool similar to Cookiecutter, utilizing Jinja2 and YAML.

It enables the creation of files by prompting the user with questions and utilizing the responses to populate templates. 

Pypyrus supports conditions on questions, allowing the dynamic display or concealment of certain questions based on previous responses.

## Installation

Coming soon

## Usage

### Create a new project

You can find some examples below:

- https://github.com/ikarys/pypyrus-simple-example[Simple example]
- https://github.com/ikarys/pypyrus-avanced-example[Advanced example]

### How to use Pypyrus

[source, bash]
----
pypyrus -u https://github.com/ikarys/pypyrus-simple-example -t my_target_folder
----

## Todo

* Manage tags on remote Git templates
* Add Shortcuts system for remote templates
* Add yaml validator for templates
* Add Jinj2 validator for templates
* Add more custom filters for Jinja2
* Study to implement a hook system
* Study possibility to have automatic field
+
[source,yaml]
----
currentDate:
    type: auto
    value: "{{ now().strftime('%Y-%m-%d') }}" or "datetime.now()"
----